AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128

Resources:
  FeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      Events:
        FeedApi:
          Type: Api
          Properties:
            Path: /feed
            Method: get
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          JWT_SECRET: !Ref JwtSecret

Parameters:
  DatabaseUrl:
    Type: String
    Description: URL de conexión a la base de datos
  JwtSecret:
    Type: String
    Description: Secreto para JWT

Outputs:
  FeedApiUrl:
    Description: "URL del endpoint GET /feed"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feed"
