AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Environment:
      Variables:
        BLUESKY_IDENTIFIER: antonio--navarro.bsky.social
        BLUESKY_PASSWORD: abdz-ahm4-et2c-sw5q
        BLUESKY_DID: did:plc:s664a67tdmo7hrihp3d44zi5

Resources:
  FetchFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda/fetchFeed.handler
      Events:
        ScheduledFetch:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Enabled: true
