name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  ENVIRONMENT: staging

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm ci
          pip install -r requirements.txt

      - name: Run tests
        run: |
          npm test
          pytest --maxfail=1 --disable-warnings -q

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy infrastructure
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh ${{ env.ENVIRONMENT }} ${{ env.AWS_REGION }}

      - name: Get API URL
        id: get-api-url
        run: |
          cd infra
          API_URL=$(terraform output -raw api_gateway_url)
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Test deployment
        run: |
          chmod +x scripts/test-deployment.sh
          ./scripts/test-deployment.sh ${{ steps.get-api-url.outputs.api_url }}

      - name: Update deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Despliegue a staging exitoso"
            echo "🌐 API URL: ${{ steps.get-api-url.outputs.api_url }}"
          else
            echo "❌ Despliegue a staging falló"
            exit 1
          fi

  notify-deployment:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: always()
    
    steps:
      - name: Notify success
        if: needs.deploy-staging.result == 'success'
        run: |
          echo "🎉 Despliegue a staging completado exitosamente"
          # Aquí puedes agregar notificaciones a Slack, email, etc.

      - name: Notify failure
        if: needs.deploy-staging.result == 'failure'
        run: |
          echo "🚨 Despliegue a staging falló"
          # Aquí puedes agregar notificaciones de error
