version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ../:/app
    command: npm run test:ci
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - '5433:5432'
