openapi: 3.0.3
info:
  title: Feed Discapacidad API
  version: 1.0.0
  description: >
    API REST para gestión y publicación del feed de contenidos de discapacidad.
  contact:
    name: Equipo de Desarrollo
    email: dev@feeddiscapacidad.com
servers:
  - url: https://api.feeddiscapacidad.com/v1
    description: Producción
  - url: https://staging.api.feeddiscapacidad.com/v1
    description: Staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        publishedAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - publishedAt
paths:
  /feed:
    get:
      summary: Obtener items del feed
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de items del feed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
